language: java
jdk:
  - oraclejdk8
services:
 - mysql
cache:
  directories:
  - $HOME/.m2
before_script:
  - mysql -e 'create database db_test;'
script: ./mvnw install -Dmaven.test.redirectTestOutputToFile=true