# Database Configuration
spring.datasource.url: 'jdbc:mysql://localhost/db'
spring.datasource.username: root
spring.datasource.password:
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

# Specify the DBMS
spring.jpa.database: MYSQL

server.port: 9000